### ISSUE TITLE
Error in Write sample

### ISSUE THREAD

**Issue by BastienFaure** [arthaud/formatstring#1]
Hello, I got that bug when trying to launch the write sample provided in your README.

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(p.generate(settings))
  File "/tmp/formatstring/formatstring/payloads.py", line 217, in generate
    writes = self._generate_writes(settings)
  File "/tmp/formatstring/formatstring/payloads.py", line 161, in _generate_writes
    self.memory[addr + 3]])
  File "/tmp/formatstring/formatstring/payloads.py", line 14, in unpack_bytes
    return struct.unpack(arch.endian_fmt + struct_fmt(len(value), False),
  File "/tmp/formatstring/formatstring/architectures.py", line 15, in struct_fmt
    assert size in formats, 'unknown size'
AssertionError: unknown size
```

I'll try to investigate during free time and keep you informed :-)

**Comment by arthaud** [comment]
Hi @BastienFaure,

Thank you for trying formatstring.

I can't reproduce the bug on my laptop neither on another computer.
Could you please tell me what version of python do you use?

Apparently, the function struct_fmt in [architectures.py](https://github.com/arthaud/formatstring/blob/master/formatstring/architectures.py#L4) got a weird size. According to the traceback, it should have size = 4. Can you check that? You could just add a print statement before the assertion. Thank you.

**Comment by BastienFaure** [comment]
Hello,

My bad, after re-reading you documentation, I noticed that I launched the sample with a 2.7 Python version. Python3 does not throw the error. Even if I don't understand the value assigned to size (29) with the older Python version, it seems to be working fine :D

**Comment by arthaud** [comment]
Hi @BastienFaure ,

Thank you. I'll close the ticket then.

About python 2: the main problem is that I use the `bytes` type in python3, that is just an alias for `str` in python 2. In `WritePayload.__setitem__`, when I iterate though `value`, you get integers in python 3 and strings in python 2! Thus, `unpack_bytes()` get a list of str (ie. `['\x01', \x02', '\x03', '\x04']`) and by applying `bytes()` again, you get:

``` python
bytes(['\x01', '\x02', '\x03', '\x04']) == "['\x01', '\x02', '\x03', '\x04']"
```

This is really not what we want.
